### PR TITLE
Fix the websocket detection

### LINKED ISSUE #90: Fix websocket to support script changes detection

### PR DESCRIPTION
**Pull request by palagdan**
Resolve #90 
websocket_notification

### CODE REVIEW

File: src/pages/ScriptPage.jsx [hunk 1]
```diff
@@ -112,12 +119,39 @@ class Script extends React.Component {
...
     cytoscape.use(expandCollapse);
     cytoscape.warnings(false);
+    this._keepAlive = this._keepAlive.bind(this);
     this.renderCytoscapeElement = this.renderCytoscapeElement.bind(this);
     this.handleRenderChange = this.handleRenderChange.bind(this);
     this.handleValidateReport = this.handleValidateReport.bind(this);
     this.handleErrorModal = this.handleErrorModal.bind(this);
   }
 
+  componentWillMount() {
```
Comment (blcham) [inline src/pages/ScriptPage.jsx:129]: I do not see that you would be closing websocket? I guess this can lead to memory leaks.

Maybe something like this should be included:
```
componentWillUnmount() {
  if (client.readyState === client.OPEN || client.readyState === client.CONNECTING) {
    client.close();
  }
}
```

File: src/pages/ScriptPage.jsx [hunk 2]
```diff
@@ -14,7 +14,7 @@ import ScriptInputOutputModal from "../components/sform/ScriptInputOutputModal.j
 import { Dropdown } from "semantic-ui-react";
 import { ICONS_MAP } from "../constants/dagreIcons.js";
 import ScriptFunctionSelection from "../components/ScriptFunctionSelection.jsx";
-import { Button } from "react-bootstrap";
+import { Button, Toast, ToastContainer } from "react-bootstrap";
```
Comment (blcham) [inline src/pages/ScriptPage.jsx:17]: I do not see where `Toast, ToastContainer` are used.

**Review by blcham — CHANGES_REQUESTED** [review]
Good job! I have 2 comments that should be resolved.

File: src/pages/ScriptPage.jsx (hunk 2 above)
Comment (blcham) [reply src/pages/ScriptPage.jsx:17]: Moreover I believe that CSS style from https://github.com/kbss-cvut/s-pipes-editor-ui/blob/master/public/main.css#L2362-L2398 can be deleted as they were introduced by `toasted-notes` which is I believe not used anymore.

The relevant commit is a406715f2f008ecb0f6044fdf0ce82c5897cb6c2

**Review by blcham — CHANGES_REQUESTED** [review]
See my comment.

File: src/pages/ScriptPage.jsx (hunk 2 above)
Comment (palagdan) [reply src/pages/ScriptPage.jsx:17]: Toast and ToastContainer from bootstrap are used for displaying the alert. 

https://github.com/kbss-cvut/s-pipes-editor-ui/pull/105/commits/c418d8a6a5eb77cd269e3a74324624e0a8cb805b#diff-5790c2ee3d329fb66628f778c77059a400fd00a3142d9fa50360d703b6a44d55R631-R649

File: src/pages/ScriptPage.jsx (hunk 1 above)
Comment (palagdan) [reply src/pages/ScriptPage.jsx:129]: done

**Review by blcham — APPROVED** [review]
LGTM
