### PR TITLE
Fix the start and finish execution dates

### LINKED ISSUE #95: Fix start and finish date.
Table of executions should provide information about time.

### PR DESCRIPTION
**Pull request by palagdan**
test_date_time

Resolve #95

Should be tested once #96 is done

notes:
- Migrate from Moment.js to Day.js as Moment.js is no longer supported, and its authors recommend using alternative libraries.
- Refactor ExecutionsPage to functional component (see #98).

### CODE REVIEW

File: src/pages/ExecutionsPage.jsx [hunk 1]
```diff
@@ -1,89 +1,89 @@
...
+                    <Row>
+                      <Col>
+                        <Link to={`/script?file=${data[ABSOLUTE_PATH]}&transformation=${data[TRANSFORMATION]}`}>
+                          <FontAwesomeIcon icon={faEdit} />
+                        </Link>
+                      </Col>
+                      <Col
+                        onClick={() => {
+                          window.open(
+                            data["http://onto.fel.cvut.cz/ontologies/s-pipes/rdf4j-transformation-id"],
```
Comment (blcham) [inline src/pages/ExecutionsPage.jsx:71]: Why we do not have this as constant somewhere?

**Review by blcham — APPROVED** [review]
LGTM, you can rebase+merge, just please resolve the issue with constant definition

File: src/pages/ExecutionsPage.jsx (hunk 1 above)
Comment (palagdan) [reply src/pages/ExecutionsPage.jsx]: done
